import LeftSideBar from "@/components/builder/LeftSideBar";
import MainBuilder from "@/components/builder/MainBuilder";
import RightSideBar from "@/components/builder/RightSideBar";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Builder",
  description: "Generated by create next app",
};

const Builder = () => {
  return (
    <div className="flex w-full justify-between p-[25px]">
      <div className="max-w-[20%]">
        <LeftSideBar />
      </div>
      <div className="w-[60%]">
        <MainBuilder />
      </div>
      <div className="max-w-[20%]">
        <RightSideBar />
      </div>
    </div>
  );
};

export default Builder;
